language: php

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/composer/files
    - $HOME/build

matrix:
  include:
    - php: 7.2
    - php: 7.3
  fast_finish: true

before_install:
  - composer validate --no-check-publish

install:
  - composer install

before_script:
  - cp src/config.php.dist src/config.php

script:
  - composer check

after_success:
  - bash <(curl -s https://codecov.io/bash)
